apiVersion: v1
kind: Pod
metadata:
  name: shankar4-pod
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: shankarss
  template:
    metadata:
      labels:
        app: shankarss   
spec:
  containers:
  - env:
    - name: APP_DEBUG
      value: "0"
    - name: APP_ENV
      value: prod
  - name: shankar-containers
    image: "dockerawsdevops1/docker-private-repo:latest"
  imagePullSecrets:
  - name: smily
    
---
apiVersion: v1
kind: Service
metadata:
  name: shankar5-service
  namespace: default
spec:
  type: Loadbalancer
  selector:
    app: shankarss
  ports:
  - nodePort: 32508
    protocol: TCP
    targetPort: 8080
    port: 80 
