apiVersion: apps/v1
kind: Deployment
metadata:
  name: shankar2-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: shankar2
  template:
    metadata:
      labels:
        app: shankar2   
spec:
  containers:
  - name: shankar-cont
    image: "dockerawsdevops1/docker-private-repo:latest"
  imagePullSecrets:
  - name: smily
    
---
apiVersion: v1
kind: Service
metadata:
  name: shankar3-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: shankar2
  ports:
  - nodePort: 32505
    protocol: TCP
    targetPort: 8080
    port: 80 
