apiVersion: v1
kind: Pod
metadata:
  name: shankar45-pod
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: shankarsss
  template:
    metadata:
      labels:
        app: shankarsss   
spec:
  containers:
  - name: shankars-containers
    image: "dockerawsdevops1/docker-private-repo:latest"
  imagePullSecrets:
  - name: smily
    
---
apiVersion: v1
kind: Service
metadata:
  name: shankar54-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: shankarsss
  ports:
  - nodePort: 32400
    protocol: TCP
    targetPort: 8080
    port: 80 
