apiVersion: v1
kind: Pod
metadata:
  name: shankar1-pod
  labels:
    app: shankara
spec:
  containers:
  - name: shankar-cont
    image: "dockerawsdevops1/docker-private-repo:latest"
  imagePullSecrets:
  - name: smily
    
---
apiVersion: v1
kind: Service
metadata:
  name: shankar2-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: shankara
  ports:
  - nodePort: 32504
    protocol: TCP
    targetPort: 8080
    port: 80 
