apiVersion: apps/v1bete1
kind: Deployment
metadata:
  name: shankar3-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: shankar3
  template:
    metadata:
      labels:
        app: shankar3   
spec:
  containers:
  - env:
    - name: APP_DEBUG
      value: "0"
    - name: APP_ENV
      value: prod
  - name: shankar-container
    image: "dockerawsdevops1/docker-private-repo:latest"
  imagePullSecrets:
  - name: smily
    
---
apiVersion: v1
kind: Service
metadata:
  name: shankar4-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: shankar3
  ports:
  - nodePort: 32506
    protocol: TCP
    targetPort: 8080
    port: 80 
